# Generated by Django 4.0.3 on 2024-02-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='theatre',
        ),
        migrations.AddField(
            model_name='show',
            name='cinemahall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screen.cinemahall'),
        ),
        migrations.AlterField(
            model_name='show',
            name='timings',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
