# Generated by Django 4.0.3 on 2024-02-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0002_remove_show_theatre_show_cinemahall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='adult_or_underaged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.aged'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.language'),
        ),
    ]
