# Generated by Django 4.0.3 on 2024-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0003_aged_language_alter_movie_adult_or_underaged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='movie',
            field=models.ManyToManyField(to='screen.movie'),
        ),
    ]
