# Generated by Django 4.0.3 on 2024-02-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0004_city_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='movie',
        ),
    ]
