# Generated by Django 4.0.3 on 2024-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0005_remove_city_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='movie',
            field=models.ManyToManyField(blank=True, to='screen.movie'),
        ),
    ]
