# Generated by Django 4.0.3 on 2024-02-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0006_city_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='google_url',
            field=models.URLField(blank=True),
        ),
    ]
