# Generated by Django 4.0.3 on 2024-02-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0008_showdate_seat_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='city',
        ),
        migrations.AddField(
            model_name='city',
            name='theatre',
            field=models.ManyToManyField(to='screen.cinemahall'),
        ),
    ]
