# Generated by Django 4.0.3 on 2024-02-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0009_remove_cinemahall_city_city_theatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='theatre',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screen.city'),
        ),
    ]
