# Generated by Django 4.0.3 on 2024-02-19 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0010_remove_city_theatre_cinemahall_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.RemoveField(
            model_name='showdate',
            name='show',
        ),
        migrations.AddField(
            model_name='show',
            name='NumOfSeats',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='ShowDate',
        ),
    ]
