# Generated by Django 4.0.3 on 2024-02-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0012_alter_show_cinemahall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cinemahall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screen.cinemahall'),
        ),
    ]
