# Generated by Django 4.0.3 on 2024-02-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0013_alter_show_cinemahall'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='price',
            field=models.IntegerField(default=150),
        ),
    ]
