# Generated by Django 4.0.3 on 2024-02-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0014_show_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='NumOfSeats',
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.CreateModel(
            name='SeatingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=5)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('theater', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='screen.cinemahall')),
            ],
        ),
    ]
