# Generated by Django 4.0.3 on 2024-02-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0015_remove_show_numofseats_alter_show_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatingconfiguration',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen.cinemahall'),
        ),
    ]
