# Generated by Django 4.0.3 on 2024-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0017_rename_price_show_avgp_show_maxp_show_minp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('movie', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cinema_hall', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('show_timings', models.CharField(max_length=100)),
                ('selected_seats', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convenience_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
