# Generated by Django 4.0.3 on 2024-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0018_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cinema_hall',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
