# Generated by Django 4.0.3 on 2024-05-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0019_alter_booking_cinema_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
