# Generated by Django 4.0.3 on 2024-05-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0020_alter_booking_show_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cinema_hall',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_timings',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
