# Generated by Django 4.0.3 on 2024-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0021_alter_booking_cinema_hall_alter_booking_show_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_timings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
