# Generated by Django 4.0.3 on 2024-05-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0022_alter_booking_show_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cinema_hall',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='show_timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
