# Generated by Django 4.0.3 on 2024-05-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen', '0023_alter_booking_cinema_hall_alter_booking_show_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cinema_hall',
            new_name='cinema_hall_id',
        ),
    ]
